#!/usr/bin/env node
// This tool parses a SotN bin for drop data, adds it the global item list
// and prints the modified list to stdout.
// Usage: tools/drop-data <path-to-rom> [indent-level]

const fs = require('fs')
const constants = require('../constants')
const items = require('../items')
const util = require('../util')

const tileIdOffset = constants.tileIdOffset
const TYPE = constants.TYPE
const ZONE = constants.ZONE
const GLOBAL_DROP = constants.GLOBAL_DROP
const zones = constants.zones
const exe = constants.exe
const enemyListOff = constants.enemyListOff 
const enemyListLen = constants.enemyListLen
const enemyDataOff = constants.enemyDataOff
const enemyDataLen = constants.enemyDataLen
const dropsOff = 0x1a

// Clear existing drop data from item list.
items.filter(function(item) {
  return !!item.tiles
}).forEach(function(item) {
  item.tiles = (item.tiles || []).filter(function(tile) {
    return typeof(tile.enemy) === 'undefined'
  })
})

// Read input bin.
const bin = fs.readFileSync(process.argv[2])
// Restore main executable.
const exeData = util.restoreFile(bin, exe)
// Restore library data.
const library = util.restoreFile(bin, zones[ZONE.LIB])
// Get enemy list.
const enemyList = library.subarray(enemyListOff, enemyListOff + enemyListLen)
// Parse enemy data.
const enemies = []
for (let i = 0; i < enemyList.length / 2; i++) {
  enemies.push({
    id: i + 1,
    offset: enemyDataOff + enemyList.readUInt16LE(2 * i) * enemyDataLen,
  })
}
// Unlisted enemies:
// Poltergeist
enemies.push({
  id: 147,
  offset: 0x9d52,
  dropCount: 1,
})
// Puppet sword
enemies.push({
  id: 148,
  offset: 0x9e6a,
  dropCount: 1,
})
// Shield
enemies.push({
  id: 149,
  offset: 0x9ee2,
  dropCount: 1,
})
// Spear
enemies.push({
  id: 150,
  offset: 0x9eba,
  dropCount: 1,
})
// Add tiles.
enemies.forEach(function(enemy) {
  const offsets = [
    enemy.offset + dropsOff + 0,
    enemy.offset + dropsOff + 2,
  ].slice(0, enemy.dropCount || 2)
  offsets.forEach(function(offset) {
    const id = exeData.readUInt16LE(offset)
    if (id === 0) {
      return
    }
    const item = items.filter(function(item) {
      if (id > tileIdOffset) {
        return item.id === (id - tileIdOffset) && [
          TYPE.WEAPON1,
          TYPE.WEAPON2,
          TYPE.SHIELD,
          TYPE.HELMET,
          TYPE.ARMOR,
          TYPE.CLOAK,
          TYPE.ACCESSORY,
          TYPE.USABLE,
        ].indexOf(item.type) !== -1
      }
      return item.id === id
    })[0]
    let address = exe.pos + offset + Math.floor(offset / 0x800) * 0x130
    item.tiles = item.tiles || []
    item.tiles.push({
      addresses: [ address ],
      enemy: enemy.id,
    })
  })
})

// The Short Sword and Red Rust dropped by the Bone Scimitars in the Entrance
// are hardcoded.
const shortSword = items.filter(function(item) {
  return item.name === 'Short Sword'
})[0]
shortSword.tiles.push({
  addresses: [ 0x04bc9324 ],
  enemy: 9,
  noOffset: true,
})
const redRust = items.filter(function(item) {
  return item.name === 'Red Rust'
})[0]
redRust.tiles.push({
  addresses: [ 0x04bc9328 ],
  enemy: 9,
  noOffset: true,
})

// Find occurences of global drops.
const globalDrops = [
  0x0003,
  0x0000,
  0x0002,
  0x0003,
  0x0003,
  0x0003,
  0x0003,
  0x0003,
  0x0003,
  0x0004,
  0x0004,
  0x0004,
  0x0004,
  0x0005,
  0x0005,
  0x0000,
  0x0000,
  0x0000,
  0x0000,
  0x0000,
  0x0000,
  0x0000,
  0x0000,
  0x0000,
  0x0000,
  0x0000,
  0x0001,
  0x0001,
  0x0002,
  0x0006,
  0x0007,
  0x00c6,
]
const buf = Buffer.alloc(2 * globalDrops.length)
globalDrops.forEach(function(id, index) {
  buf.writeUInt16LE(id, 2 * index)
})
const addresses = []
let i = 0
while (i < bin.length - buf.length) {
  if (bin.subarray(i, i + buf.length).equals(buf)) {
    addresses.push(i)
    i += buf.length
  } else {
    i++
  }
}
globalDrops.forEach(function(id, index) {
  const item = util.itemFromTileId(items, id)
  item.tiles = item.tiles || []
  item.tiles.push({
    addresses: addresses.map(function(address) {
      return address + 2 * index
    }),
    enemy: GLOBAL_DROP,
    global: true,
  })
})

// Format data.
const indent = parseInt(process.argv[3] || 2)
const spaces = Array(indent).fill(' ').join('')
console.log(spaces + 'const items = ' + util.formatObject(items, indent))
