#!/usr/bin/env node
// This tool parses a SotN bin for relic data and prints
// the list to stdout.
// Usage: tools/relic-data <path-to-rom> [indent-level]

const fs = require('fs')
const constants = require('../constants')
const items = require('../items')
const relics = require('../relics')
const util = require('../util')

const tileIdOffset = constants.tileIdOffset
const TYPE = constants.TYPE
const typeNames = constants.typeNames
const RELIC = constants.RELIC
const ZONE = constants.ZONE
const zones = constants.zones

const rewardAddresses = [
  0x047a53c4,
  0x04aa26b0,
  0x054b3ac8,
  0x05574d60,
  0x059bdb08,
  0x05fac75c,
  0x0606f9e0,
  0x060fe614,
  0x061a80a8,
  0x0624b968,
  0x06306a90,
  0x063ad9c8,
  0x06472310,
  0x06509e30,
  0x065921c8,
  0x06622610,
  0x066b4998,
  0x067437b0,
  0x067d160c,
  0x06866130,
  0x069d2af8,
  0x06a61adc,
]

function isRelic(entity) {
  return entity.entity.readUInt16LE(4) === 0x000b
}

function findRelicAddresses(zoneId, zone, data) {
  data = util.restoreFile(data, zone)
  const entities = util.entityOffsets(data)
  entities.filter(isRelic).forEach(function(entity) {
    const id = entity.entity[8]
    const relic = relics.filter(function(relic) {
      return relic.id === id
    })[0]
    const addresses = entity.addresses.map(function(address) {
      return util.romOffset(zone, address + 8)
    })
    Array.prototype.push.apply(relic.addresses, addresses)
  })
}

function relicFromAbility(ability) {
  return relics.filter(function(relic) {
    return relic.ability === ability
  })[0]
}

// Strip addresses from existing relic data.
relics.forEach(function(relic) {
  relic.addresses = []
})

// Add relics that aren't in entity data.
relicFromAbility(RELIC.SKILL_OF_WOLF).addresses.push(
  util.romOffset(zones[ZONE.NZ0], 0x0fa2),
)
relicFromAbility(RELIC.JEWEL_OF_OPEN).addresses.push(
  util.romOffset(zones[ZONE.LIB], 0x14d4),
)
relicFromAbility(RELIC.BAT_CARD).addresses.push(
  util.romOffset(zones[ZONE.NZ0], 0x0fa0),
)
relicFromAbility(RELIC.RING_OF_VLAD).addresses.push(
  util.romOffset(zones[ZONE.RNZ1], 0x0272fc),
  util.romOffset(zones[ZONE.RNZ1], 0x02c85c),
)

// Read input bin.
const bin = fs.readFileSync(process.argv[2])

// Read entity data.
zones.forEach(function(zone, zoneId) {
  findRelicAddresses(zoneId, zone, bin)
})

// Patch reward data.
const vladRelics = [
  RELIC.HEART_OF_VLAD,
  RELIC.TOOTH_OF_VLAD,
  RELIC.RIB_OF_VLAD,
  RELIC.RING_OF_VLAD,
  RELIC.EYE_OF_VLAD,
].map(function(ability) {
  return relics.filter(function(relic) {
    return relic.ability === ability
  })[0]
})
rewardAddresses.forEach(function(address) {
  vladRelics.forEach(function(relic, index) {
    relic.addresses.push(address + 0x22 + 2 * index)
  })
})

// Format data.
const indent = parseInt(process.argv[3] || 2)
const spaces = Array(indent).fill(' ').join('')
console.log(spaces + 'const relics = ' + util.formatObject(relics, indent))
